import React from 'react';

const Popular = () => {
  return (
    <div>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur aliquid tempore doloribus est magnam vero, cum quae fuga non quibusdam et consequuntur nihil, distinctio tenetur a. Aliquam repellat vitae molestias. Nobis velit excepturi reprehenderit neque qui nesciunt asperiores vero, omnis voluptatibus fuga id in ipsam similique sequi eligendi sapiente nisi rem hic porro, odit esse, placeat fugiat. Provident odit iure tempore! Reprehenderit beatae rerum asperiores aut totam quibusdam aspernatur unde temporibus laboriosam ipsam in, explicabo mollitia voluptatibus, consectetur vel amet! Architecto iure sed amet aliquam ipsam at voluptatum illum excepturi velit ea doloremque, rerum nulla accusantium delectus quae quaerat! Modi neque in cumque, et explicabo aspernatur iste alias temporibus maxime? Maxime temporibus nulla architecto dignissimos, eveniet corrupti reiciendis fugiat, harum adipisci omnis modi provident eum fugit! Dolorum suscipit deleniti aspernatur consequuntur, dolores mollitia? Ullam quo at nulla? Harum esse, voluptatum fuga autem reiciendis distinctio! Expedita aperiam nisi at, doloribus cum facilis porro ea delectus vero ad explicabo necessitatibus. Cum omnis provident iste itaque sit neque molestias temporibus voluptate odit. Esse minus aspernatur vel, optio earum iste aut reprehenderit labore animi doloribus, unde consectetur a deleniti pariatur veniam voluptatum voluptatem amet quod sapiente repudiandae delectus, accusantium at architecto. Nulla mollitia nobis aperiam quibusdam cum, amet nemo dolor, beatae est tempore voluptatem laboriosam commodi neque dicta vitae ab exercitationem labore eius voluptatum animi asperiores. Illum fugit cum harum vero reiciendis obcaecati voluptatibus facere officiis? Necessitatibus repellat cupiditate illum eos ducimus natus eius, ratione eum minima nisi reprehenderit! Nam ipsa magnam nihil laudantium voluptatum iusto necessitatibus quo, sed amet eum voluptatibus, quaerat vero reiciendis, id corporis totam labore! Voluptate dicta vitae numquam distinctio obcaecati ab sunt praesentium consectetur at assumenda eos, atque temporibus ullam, earum ea accusamus nam recusandae iusto explicabo sequi magni minima nihil. Beatae totam obcaecati recusandae repudiandae eos! Totam, autem.
    </div>
  );
};

export default Popular;